services:
  - type: web
    name: abaq-alkahrab
    runtime: python
    buildCommand: pip install -r requirements.txt || echo "No dependencies"
    startCommand: python3 server.py 8080 0.0.0.0
    envVars:
      - key: PORT
        value: 8080
      - key: HOST
        value: 0.0.0.0
